########
# CoDi #
########

XGeM:
  type: XGeM
  symbol: XGeM
  find_unused_parameters: true
  args:
    autokl_cfg: MODEL(sd_autoencoder)
    optimus_cfg: MODEL(optimus_vae)
    clip_cfg: MODEL(clip_frozen)
    unet_config: MODEL(openai_unet_XGeM)
    beta_linear_start: 0.00085
    beta_linear_end: 0.012
    timesteps: 1000
    vision_scale_factor: 0.18215
    text_scale_factor: 4.3108
    use_ema: false
    parameterization : "eps"
